### ISSUE TITLE
Make OAF select images with tags

### ISSUE THREAD

**Issue by notionparallax** [notionparallax/ShadowWolf#429]
OA doesn't allow freeform tagging, we can get around this by putting freeform tags into the Description field. 

Users would see:

> This is a photo of a unicorn and a double rainbow, it shows refraction at its finest. [[Unicorn, Rainbow, Refraction]]

As oaf is a wrapper that will get out of the way once the OA API isn't so shit, when freeform tags are a thing we can do a migration.

http://help.axomic.com/07_Technical_Stuff/APIs_and_Integration/REST_API/Files

description is a property on File

Use case
=======
When there are multiple project sheets then each one will need different images, e.g. you'd ask oaf for the top three images tagged 'retail'

**Comment by Dawil** [comment]
Progress: d32aad726e3babb9ed12a0eede721ef7bf81c52a
