### ISSUE TITLE
Make project sheet text orderable

### ISSUE THREAD

**Issue by elsayoung** [notionparallax/ShadowWolf#456]
one line grab isn't coming up

**Comment by elsayoung** [comment]
It's still not working

**Comment by notionparallax** [comment]
Text is put on the project page in the order that it is on the `text` tab.
This needs to be solved by some way of moving the text sections around so that their order gets nudged too.

**Comment by Dawil** [comment]
May use either this http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/simple or a simple up/down button. I've a preference for not adding more dependencies so I'll probably go with the up/down button.

**Comment by notionparallax** [comment]
That's pretty cute, but I'm inclined to agree. Up down is surely going to
be easier

**Comment by notionparallax** [comment]
#514 for more
