### ISSUE TITLE
not sure how to change fields for multiple sections of a project

### ISSUE THREAD

**Issue by elsayoung** [notionparallax/ShadowWolf#458]
Some projects have different sections to them, and the value, timing, size etc. are different to the main project. I'm not sure how to change them.

An example is ELF 2B - Enhanced Land Force Stage 2 Phase 2B Facilities Project B0903009. There are 3 parts to the project and some fields are different according to the project sheets

For reference:
W:\B0903009_WONCO\Text Files\Project Sheet
W:\B0903009_Living-in\Project sheets\SS
W:\B0903009\Text

**Comment by elsayoung** [comment]
also would pictures change under the subsections?

**Comment by notionparallax** [comment]
@elsayoung is this still an issue?

**Comment by elsayoung** [comment]
I don't think so
