### ISSUE TITLE
make final budget on legacy be plural and tagged

### ISSUE THREAD

**Issue by elsayoung** [notionparallax/ShadowWolf#471]
Is it possible to put multiple entries/details in budget fields?

Eg. I need to put 
$1,310,640 – Base building
$1.05M - Fit-out

into "Construction final" but it won't allow it

**Comment by elsayoung** [comment]
Also for the "Final Budget" field in the Legacy tab

**Comment by notionparallax** [comment]
make final budget on legacy be plural and tagged

**Comment by Dawil** [comment]
Adding a string field to describe the budget so we know what the budget refers to (Project sheets may end up having multiple budgets). 

Also will need to migrate existing final budgets. I'll do this by leaving final_budget on legacy, running a data migration, and in a later deploy deleting the legacy.final_budget field.

**Comment by elsayoung** [comment]
Can we do this for the final dates (legacy tab) too?
