### ISSUE TITLE
new measurement box doesn't fit the number itself

### ISSUE THREAD

**Issue by elsayoung** [notionparallax/ShadowWolf#477]
eg. east sale redevelopment - the numbers are cutting into the title "measurement"

**Comment by elsayoung** [comment]
Also for referees box

**Comment by elsayoung** [comment]
![image](https://cloud.githubusercontent.com/assets/10539549/5847612/2608428e-a223-11e4-8605-653e02663fa9.png)

**Comment by notionparallax** [comment]
also for text templates...
