### ISSUE TITLE
Add a currency field and a confidential field to budget

### ISSUE THREAD

**Issue by elsayoung** [notionparallax/ShadowWolf#478]
eg. GBP$120M / AUD$182M

For the 2012 London Olympics Athlete's Village

**Comment by elsayoung** [comment]
or the word confidential

**Comment by Dawil** [comment]
Over to you, @notionparallax, as of 0d46e1f7bc0c6f537698bf7464a58cb7ec16b0fd .

**Comment by notionparallax** [comment]
@dawil - just to add some UI?

**Comment by Dawil** [comment]
Yep. You can use the variable subobject to maybe select a currency symbol

**Comment by notionparallax** [comment]
These need to be on legacy budget. Sorry for not being specific
