### ISSUE TITLE
Add a field for associated projects

### ISSUE THREAD

**Issue by notionparallax** [notionparallax/ShadowWolf#485]

**Comment by notionparallax** [comment]
for example, ASB north wharf is related to the theatre.

It should be a plural with fields for:

[generated project name]
Project number (string)
Relationship description

**Comment by Dawil** [comment]
I think getting the typeahead for this will have to be a separate issue since there's a bit of work involved in that.

**Comment by Dawil** [comment]
Also this would usually involve a join table. Since mongo doesn't lend itself to such a style this issue is a little more complicated than would be ideal. I'll handle this later.

**Comment by notionparallax** [comment]
@dawil just make it a 1 way relationship for the moment. The associations might not be bidirectional

e.g. if you build a house, then get an extension. The extension is related to the house, but not really the other way around.

**Comment by Dawil** [comment]
see #547 for typeahead support

**Comment by notionparallax** [comment]
Needs to be stubbed
