### ISSUE TITLE
OAF isn't fetching photos according to their ranking

### ISSUE THREAD

**Issue by notionparallax** [notionparallax/ShadowWolf#491]

**Comment by notionparallax** [comment]
This will probably be fixed by the update to tagged images

**Comment by Dawil** [comment]
Also look at #503 for possible error handling solutions

**Comment by Dawil** [comment]
So I think what happened was I got the OAF side of things working then I didn't get around to plugging it in to the angular side of things. So nothing's broken it's just unimplemented which will mean things are easier.
