### ISSUE TITLE
Phone list - staff who have left

### ISSUE THREAD

**Issue by RosaCotrona** [notionparallax/ShadowWolf#502]
The gray line which distinguishes these people from current staff is not clear enough.

**Comment by notionparallax** [comment]
Is this more obvious?
![image](https://cloud.githubusercontent.com/assets/1865196/6014568/d38dab10-abba-11e4-8e07-4b566b090b55.png)
or this:
![image](https://cloud.githubusercontent.com/assets/1865196/6014581/105bd54e-abbb-11e4-92ba-0b55ae152416.png)
Do you have any thoughts?
