### ISSUE TITLE
Suggestion: Add a field for 'Building Owner' and 'Builder' in the Relationships section

### ISSUE THREAD

**Issue by elsayoung** [notionparallax/ShadowWolf#524]
A suggestion from Domino Risch.

Because those are the things that most often become complicated

**Comment by notionparallax** [comment]
This is a bigger issue that we need to address.
There are lots of relationships to capture.
This will come when we have a proper contacts list in deltec, but in general it needs to be

```
entity
relationship name
start date
end date
```
so that is things like consultants, clients, building owners. That also captures how it changes over time.

**Comment by Dawil** [comment]
@notionparallax can I get a spec for this? Parent model, model name, model fields, relationship with parent?

**Comment by notionparallax** [comment]
@dawil updated
