### ISSUE TITLE
Project stage field

### ISSUE THREAD

**Issue by edyabsley** [notionparallax/ShadowWolf#534]
Could we have a field on the summary tab of P+P to note where a project finished?

ie BD, Design Comp, Construction, etc etc.

At this stage we can indicate this in the notes field but if it's searchable that would be more helpful.

**Comment by notionparallax** [comment]
Ideally this would be defined by the phases section. Especially once we've
refactored it so that it is a timeline.

For the moment it would be a useful addition

**Comment by edyabsley** [comment]
Yes indeed.

Any way we can name phases instead of just calling them 0, 1, 2, 3 etc?

**Comment by notionparallax** [comment]
fields:
```
final_stage|Final Stage | string | This captures the last stage that this project was worked on. Was it just a submission? Did we take it all the way through?
notes|Notes | text |Anything to say about this? Did we stop at DD, but then put it on hold?
```

 on building.legacy, goes on the summary page

**Comment by notionparallax** [comment]
actually lets leave this until we've worked out the phases thing. @edyabsley just put the final phase in the notes for now
