### ISSUE TITLE
BCA Classification has gone weird

### ISSUE THREAD

**Issue by elsayoung** [notionparallax/ShadowWolf#546]
It's tagged each individual letter, so if it was class 9 it would be tagged c, l, a, s, s, 9

**Comment by Dawil** [comment]
I think that I've prevented it from happening to any existing projects however I'll need a little while and a re-deploy to fix it for new projects that get created.

Also I can't identify any projects that have been affected like you described, besides maybe `Sandvik Headquarters - B021011`. If there are other examples that are still broken please let me know.

**Comment by Dawil** [comment]
Deployed bd50375e73ea5d4454e122e2f9429045753b5e6b just now so newly created projects should also work. I'll just check there aren't any new projects as of the last hour that need addressing.

**Comment by elsayoung** [comment]
Thanks Dave. I had a quick look and couldn't see any, but I was pretty sure
there were quite a few before

**Comment by Dawil** [comment]
I ran a query to fix what I could. I'm going to close this issue now but reopen it if you find something broken in the same way.
