### ISSUE TITLE
Text entry has disappeared

### ISSUE THREAD

**Issue by bsul9430** [notionparallax/ShadowWolf#602]
Under the text tab there are no boxes for text entry anymore

**Comment by bsul9430** [comment]
For the Bay street glebe project anyway S1311525

**Comment by Dawil** [comment]
There were 15 projects that had this problem (date is when they were created):

* B1106003	2015-02-17 02:23:28 UTC
* B1103502	2015-02-17 01:51:13 UTC
* B1312001	2015-02-16 05:53:22 UTC
* B0903514	2015-02-18 06:05:07 UTC
* B0701513	2015-02-18 02:19:38 UTC
* B0702513	2015-02-18 02:24:34 UTC
* B0701511	2015-02-18 02:18:16 UTC
* B030617	2015-02-18 02:38:44 UTC
* s1311525	2015-02-17 23:29:26 UTC
* B030557	2015-02-18 01:15:38 UTC
* s1210003	2015-02-17 22:36:52 UTC
* B0701502	2015-02-18 02:16:29 UTC
* B0611515	2015-02-18 06:32:50 UTC
* B0903609	2015-02-19 01:47:15 UTC
* B0702005	2015-02-19 05:27:43 UTC

They should all be fixed.
