### ISSUE TITLE
Key dates

### ISSUE THREAD

**Issue by danielelias** [notionparallax/ShadowWolf#608]
Key dates "dirty name box" and "name box" should be one box instead of two and could be smaller in width.
![1](https://cloud.githubusercontent.com/assets/10877203/6888705/fd12ac00-d6d1-11e4-8786-b00bfe261e67.PNG)

**Comment by hinds89** [comment]
* I think `Dirty date` can be removed all together (move data to an entry in key dates - if there is any, I have never seen anything in 'dirty date' field)
