### ISSUE TITLE
make project sheets printable en mass

### ISSUE THREAD

**Issue by notionparallax** [notionparallax/ShadowWolf#610]
Make some kind of script and associated modifications to the markup etc that will allow the project sheets to be printed as a batch.
I'd imagine that this is via the browser as something like prince is proprietary and hard to work with.

Issues to overcome will be making sure that the latest images have loaded and that each project sheet has a good filename.

It will rely on #486 to ensure that the layout is correct.

The back story is that the powers that be aren't happy with the current project sheet layout. PTy is going to update the layout, but that means reformatting 2k indesign files. This way we can make all those PDFs in a fraction of the time. This also make it clear that P+P is the single source of truth.

**Comment by notionparallax** [comment]
`<meta name="title" content="+300 Awesome Free Things for Entrepreneurs and Startups — Startups, Wanderlust &amp; Life Hacking — Medium">`

**Comment by Dawil** [comment]
So this *works*. It could be made faster in numerous ways and is maybe unreliable but I'm going to close this issue.
