### ISSUE TITLE
Multiple locations to enter client

### ISSUE THREAD

**Issue by hinds89** [notionparallax/ShadowWolf#640]
Currently the same client is entered **3 times** in the following locations (can it be made so that there is just one entry of client):
* `Contracting Party` on **People** tab
* As an entry in External Team on **People** tab
* `Client` on **Phases** tab

**Comment by Dawil** [comment]
There's a single, plural and in phases. Delete/migrate the single and phases into the plural then create a list of probably cases of duplicates that have been created from this migration.

**Comment by notionparallax** [comment]
kill: people>client 
kill: relationships>client
kill:phases>client

migrate into external team

**Comment by Dawil** [comment]
Relationships>client has been merged by hand and is gone (#658).

@notionparallax can we discuss how the fields in people>client get funneled into external team? Likewise phases>client.

**Comment by Dawil** [comment]
The resolution was that people>client would be broken up thus:

contracting party: val1 => entity: val1, role: 'contracting party'
key2: val2 => entity: val2, role: key2
...
