### ISSUE TITLE
Blank Dates currently showing up as 1970

### ISSUE THREAD

**Issue by hinds89** [notionparallax/ShadowWolf#654]
Currently if the start or finish date are left blank, the project sheet shows January 1970 (see picture).  Perhaps leave blank instead - so if just a completed date is entered have 'Completed - date'.
![image](https://cloud.githubusercontent.com/assets/12288522/8076414/89543bac-0f8f-11e5-8a5e-5061520cbb01.png)

**Comment by notionparallax** [comment]
relate to #698
