### ISSUE TITLE
Create field 'Original Architect' to go directly below Attribution

### ISSUE THREAD

**Issue by hinds89** [notionparallax/ShadowWolf#656]
Most projects should have attribution BVN, but need a way to capture who the original architect was (e.g. Attribution for Grose Bradley projects is 'BVN' but original architect is 'Grose Bradley').  The `Original Architect` field should be placed directly below `Attribution`.

*This request came from Mitch's interview with James*

**Comment by notionparallax** [comment]
Label: Original Architect
Type: text
help: Some projects were completed by a different entity. If this project was done by Bligh Lobb then you put BVN in the attribution and Bligh Lobb in the Original Architect field.


factory: ["PINK", "Bligh Lobb", "BVN Architecture", BVN Donovan Hill]
