### ISSUE TITLE
Remove Relationships field (depreciated)

### ISSUE THREAD

**Issue by hinds89** [notionparallax/ShadowWolf#658]
- Remove Relationships field (depreciated), first perform the below actions:
 - Create a list of all projects where Relationships are filled in and the text has not been moved to the relevant description field of external team
 - Data guys can go into each project on the list and merge data before deleting the Relationships section
![image](https://cloud.githubusercontent.com/assets/12288522/8152084/f73b36d2-135b-11e5-9137-eaa134ec2506.png)

**Comment by notionparallax** [comment]
needs a migration

**Comment by Dawil** [comment]
@hinds89 can you please migrate these relationship descriptions into external team:

- [ ] [B040712](http://phonelist.bvn.com.au:9000/#/projects/B040712)
- [ ] [B0906507](http://phonelist.bvn.com.au:9000/#/projects/B0906507)
- [ ] [C010324](http://phonelist.bvn.com.au:9000/#/projects/C010324)
- [ ] [B1210076](http://phonelist.bvn.com.au:9000/#/projects/B1210076)
- [ ] [B1210077](http://phonelist.bvn.com.au:9000/#/projects/B1210077)
- [ ] [B0701002](http://phonelist.bvn.com.au:9000/#/projects/B0701002)
- [ ] [B020508](http://phonelist.bvn.com.au:9000/#/projects/B020508)
- [ ] [B030801](http://phonelist.bvn.com.au:9000/#/projects/B030801)
- [ ] [B0705013](http://phonelist.bvn.com.au:9000/#/projects/B0705013)
- [ ] [B1201002](http://phonelist.bvn.com.au:9000/#/projects/B1201002)
- [ ] [s1501010](http://phonelist.bvn.com.au:9000/#/projects/s1501010)
- [ ] [S1501509](http://phonelist.bvn.com.au:9000/#/projects/S1501509)
- [ ] [s1407002](http://phonelist.bvn.com.au:9000/#/projects/s1407002)
- [ ] [S1406505](http://phonelist.bvn.com.au:9000/#/projects/S1406505)
- [ ] [S1408002](http://phonelist.bvn.com.au:9000/#/projects/S1408002)
- [ ] [S1502005](http://phonelist.bvn.com.au:9000/#/projects/S1502005)
- [ ] [S1411004](http://phonelist.bvn.com.au:9000/#/projects/S1411004)
- [ ] [S1406504](http://phonelist.bvn.com.au:9000/#/projects/S1406504)
- [ ] [S1411001](http://phonelist.bvn.com.au:9000/#/projects/S1411001)
- [ ] [B0903009](http://phonelist.bvn.com.au:9000/#/projects/B0903009)
- [ ] [B1103008](http://phonelist.bvn.com.au:9000/#/projects/B1103008)
- [ ] [S1005001](http://phonelist.bvn.com.au:9000/#/projects/S1005001)
- [ ] [S060607](http://phonelist.bvn.com.au:9000/#/projects/S060607)
- [ ] [S1109015](http://phonelist.bvn.com.au:9000/#/projects/S1109015)
- [ ] [S060404](http://phonelist.bvn.com.au:9000/#/projects/S060404)
- [ ] [S1203005](http://phonelist.bvn.com.au:9000/#/projects/S1203005)
- [ ] [s051252](http://phonelist.bvn.com.au:9000/#/projects/s051252)
- [ ] [B010101](http://phonelist.bvn.com.au:9000/#/projects/B010101)
- [ ] [B011114](http://phonelist.bvn.com.au:9000/#/projects/B011114)
- [ ] [M1103005](http://phonelist.bvn.com.au:9000/#/projects/M1103005)
- [ ] [B011117](http://phonelist.bvn.com.au:9000/#/projects/B011117)
- [ ] [B021011](http://phonelist.bvn.com.au:9000/#/projects/B021011)
- [ ] [S0705003](http://phonelist.bvn.com.au:9000/#/projects/S0705003)
- [ ] [B031112](http://phonelist.bvn.com.au:9000/#/projects/B031112)
- [ ] [B1210065](http://phonelist.bvn.com.au:9000/#/projects/B1210065)
- [ ] [S0802002](http://phonelist.bvn.com.au:9000/#/projects/S0802002)
- [ ] [B1006510](http://phonelist.bvn.com.au:9000/#/projects/B1006510)
- [ ] [B0809007](http://phonelist.bvn.com.au:9000/#/projects/B0809007)
- [ ] [B0908004](http://phonelist.bvn.com.au:9000/#/projects/B0908004)
- [ ] [S1108001](http://phonelist.bvn.com.au:9000/#/projects/S1108001)
- [ ] [B0803004](http://phonelist.bvn.com.au:9000/#/projects/B0803004)
- [ ] [S1001003](http://phonelist.bvn.com.au:9000/#/projects/S1001003)
- [ ] [B0609008](http://phonelist.bvn.com.au:9000/#/projects/B0609008)
- [ ] [B1012006](http://phonelist.bvn.com.au:9000/#/projects/B1012006)
- [ ] [B1207001](http://phonelist.bvn.com.au:9000/#/projects/B1207001)
- [ ] [B001079](http://phonelist.bvn.com.au:9000/#/projects/B001079)
- [ ] [B1302011](http://phonelist.bvn.com.au:9000/#/projects/B1302011)
- [ ] [B1103012](http://phonelist.bvn.com.au:9000/#/projects/B1103012)
- [ ] [B1210053](http://phonelist.bvn.com.au:9000/#/projects/B1210053)
- [ ] [B1108007](http://phonelist.bvn.com.au:9000/#/projects/B1108007)
- [ ] [B990503](http://phonelist.bvn.com.au:9000/#/projects/B990503)
- [ ] [B1210040](http://phonelist.bvn.com.au:9000/#/projects/B1210040)
- [ ] [B1303002](http://phonelist.bvn.com.au:9000/#/projects/B1303002)
- [ ] [B1210078](http://phonelist.bvn.com.au:9000/#/projects/B1210078)
- [ ] [B1210085](http://phonelist.bvn.com.au:9000/#/projects/B1210085)
- [ ] [B050314](http://phonelist.bvn.com.au:9000/#/projects/B050314)
- [ ] [B011209](http://phonelist.bvn.com.au:9000/#/projects/B011209)
- [ ] [S1403005](http://phonelist.bvn.com.au:9000/#/projects/S1403005)
- [ ] [B1210073](http://phonelist.bvn.com.au:9000/#/projects/B1210073)
- [ ] [B1210035](http://phonelist.bvn.com.au:9000/#/projects/B1210035)
- [ ] [B0806503](http://phonelist.bvn.com.au:9000/#/projects/B0806503)
- [ ] [M0911001](http://phonelist.bvn.com.au:9000/#/projects/M0911001)
- [ ] [B1210071](http://phonelist.bvn.com.au:9000/#/projects/B1210071)
- [ ] [B1210069](http://phonelist.bvn.com.au:9000/#/projects/B1210069)
- [ ] [B1203009](http://phonelist.bvn.com.au:9000/#/projects/B1203009)
- [ ] [B1210052](http://phonelist.bvn.com.au:9000/#/projects/B1210052)
- [ ] [B990504](http://phonelist.bvn.com.au:9000/#/projects/B990504)
- [ ] [B1210060](http://phonelist.bvn.com.au:9000/#/projects/B1210060)
- [ ] [B1210066](http://phonelist.bvn.com.au:9000/#/projects/B1210066)
- [ ] [B0612001](http://phonelist.bvn.com.au:9000/#/projects/B0612001)
- [ ] [S1210005](http://phonelist.bvn.com.au:9000/#/projects/S1210005)
- [ ] [B0705006](http://phonelist.bvn.com.au:9000/#/projects/B0705006)
- [ ] [B1005004](http://phonelist.bvn.com.au:9000/#/projects/B1005004)
- [ ] [B0807006](http://phonelist.bvn.com.au:9000/#/projects/B0807006)
- [ ] [B1202001](http://phonelist.bvn.com.au:9000/#/projects/B1202001)
- [ ] [B1207005](http://phonelist.bvn.com.au:9000/#/projects/B1207005)
- [ ] [C0909003](http://phonelist.bvn.com.au:9000/#/projects/C0909003)
- [ ] [B020612](http://phonelist.bvn.com.au:9000/#/projects/B020612)
- [ ] [B031215](http://phonelist.bvn.com.au:9000/#/projects/B031215)
- [ ] [B1011002](http://phonelist.bvn.com.au:9000/#/projects/B1011002)
- [ ] [B0705002](http://phonelist.bvn.com.au:9000/#/projects/B0705002)
- [ ] [M0912007](http://phonelist.bvn.com.au:9000/#/projects/M0912007)
- [ ] [S060527](http://phonelist.bvn.com.au:9000/#/projects/S060527)
- [ ] [S0712001](http://phonelist.bvn.com.au:9000/#/projects/S0712001)
- [ ] [S0607018](http://phonelist.bvn.com.au:9000/#/projects/S0607018)
- [ ] [B0807005](http://phonelist.bvn.com.au:9000/#/projects/B0807005)
- [ ] [S1012007](http://phonelist.bvn.com.au:9000/#/projects/S1012007)
- [ ] [S1107008](http://phonelist.bvn.com.au:9000/#/projects/S1107008)
- [ ] [S0706003](http://phonelist.bvn.com.au:9000/#/projects/S0706003)
- [ ] [s060102](http://phonelist.bvn.com.au:9000/#/projects/s060102)
- [ ] [S050101](http://phonelist.bvn.com.au:9000/#/projects/S050101)
- [ ] [S1501005](http://phonelist.bvn.com.au:9000/#/projects/S1501005)
- [ ] [S1501505](http://phonelist.bvn.com.au:9000/#/projects/S1501505)
- [ ] [S1502502](http://phonelist.bvn.com.au:9000/#/projects/S1502502)
- [ ] [S1409520](http://phonelist.bvn.com.au:9000/#/projects/S1409520)
- [ ] [s1409521](http://phonelist.bvn.com.au:9000/#/projects/s1409521)
- [ ] [S1212002](http://phonelist.bvn.com.au:9000/#/projects/S1212002)
- [ ] [S1501007](http://phonelist.bvn.com.au:9000/#/projects/S1501007)
- [ ] [s1412001](http://phonelist.bvn.com.au:9000/#/projects/s1412001)
- [ ] [S1412004](http://phonelist.bvn.com.au:9000/#/projects/S1412004)
- [ ] [S1502505](http://phonelist.bvn.com.au:9000/#/projects/S1502505)
- [ ] [S1405505](http://phonelist.bvn.com.au:9000/#/projects/S1405505)
- [ ] [S1309002](http://phonelist.bvn.com.au:9000/#/projects/S1309002)
- [ ] [S1409524](http://phonelist.bvn.com.au:9000/#/projects/S1409524)
- [ ] [S1409533](http://phonelist.bvn.com.au:9000/#/projects/S1409533)
- [ ] [S1409004](http://phonelist.bvn.com.au:9000/#/projects/S1409004)
- [ ] [S1407005](http://phonelist.bvn.com.au:9000/#/projects/S1407005)
- [ ] [S1409519](http://phonelist.bvn.com.au:9000/#/projects/S1409519)
- [ ] [c1001007](http://phonelist.bvn.com.au:9000/#/projects/c1001007)
- [ ] [B1106003](http://phonelist.bvn.com.au:9000/#/projects/B1106003)
- [ ] [B0802004](http://phonelist.bvn.com.au:9000/#/projects/B0802004)
- [ ] [S020216](http://phonelist.bvn.com.au:9000/#/projects/S020216)
- [ ] [B0808008](http://phonelist.bvn.com.au:9000/#/projects/B0808008)
- [ ] [B0804007](http://phonelist.bvn.com.au:9000/#/projects/B0804007)
- [ ] [S1206005](http://phonelist.bvn.com.au:9000/#/projects/S1206005)
- [ ] [C0903003](http://phonelist.bvn.com.au:9000/#/projects/C0903003)
- [ ] [M0911003](http://phonelist.bvn.com.au:9000/#/projects/M0911003)
- [ ] [B040717](http://phonelist.bvn.com.au:9000/#/projects/B040717)
- [ ] [S0804002](http://phonelist.bvn.com.au:9000/#/projects/S0804002)
- [ ] [M1007001](http://phonelist.bvn.com.au:9000/#/projects/M1007001)
- [ ] [B1210075](http://phonelist.bvn.com.au:9000/#/projects/B1210075)
- [ ] [B1205005](http://phonelist.bvn.com.au:9000/#/projects/B1205005)
- [ ] [B0705010](http://phonelist.bvn.com.au:9000/#/projects/B0705010)
- [ ] [S040108](http://phonelist.bvn.com.au:9000/#/projects/S040108)
- [ ] [B0712003](http://phonelist.bvn.com.au:9000/#/projects/B0712003)
- [ ] [B1309513](http://phonelist.bvn.com.au:9000/#/projects/B1309513)
- [ ] [S0910004](http://phonelist.bvn.com.au:9000/#/projects/S0910004)
- [ ] [s1009005](http://phonelist.bvn.com.au:9000/#/projects/s1009005)
- [ ] [S1009002](http://phonelist.bvn.com.au:9000/#/projects/S1009002)
- [ ] [S1109006](http://phonelist.bvn.com.au:9000/#/projects/S1109006)
- [ ] [S1502509](http://phonelist.bvn.com.au:9000/#/projects/S1502509)
- [ ] [B1210030](http://phonelist.bvn.com.au:9000/#/projects/B1210030)
- [ ] [S1501504](http://phonelist.bvn.com.au:9000/#/projects/S1501504)
- [ ] [B030708](http://phonelist.bvn.com.au:9000/#/projects/B030708)

**Comment by hinds89** [comment]
@Dawil DONE - Should be good to go.  Maybe run a check again for non-blank relationship fields, just to check we haven't missed any or architects haven't filled this in after it's been emptied.  Let me know if there are still any projects with data in those fields.  Thanks to Yudi and @danielmok

**Comment by notionparallax** [comment]
you guys are unstoppable!

**Comment by Dawil** [comment]
@hinds89 all but one are done. [S060526](http://phonelist.bvn.com.au:9000/#/projects/S060527) still has some text in the client field. However an entity in external team exists below containing the exact text so I'll clean this up. I'll remove the relationship field from the form.
