### ISSUE TITLE
Add Comments field to Final Budget items

### ISSUE THREAD

**Issue by hinds89** [notionparallax/ShadowWolf#661]
- Add a **Comments** field to final Budget Entries 
![image](https://cloud.githubusercontent.com/assets/12288522/8152366/6c96a3e6-135f-11e5-8542-fe9b87c04bf7.png)

**Comment by notionparallax** [comment]
@hinds89 what sorts of comments go in here?

**Comment by hinds89** [comment]
Yere, not sure, I did see a project that had a comment in budget that needed somewhere to go in Final Budget (but forgotten project number and what the comment said)
There could be comments like (although these may be able to be stored somewhere else?):
 - Project was over budget
 - Good value for money
 - this job made a profit/loss

**Comment by hinds89** [comment]
An example comment to go in the comments field: "BVN estimates as final costs unknown to us"
(See - http://10.22.140.67:9000/#/projects/M0710006)
