### ISSUE TITLE
Remove Dirty awards, pictures and testimonial (Legacy tab)

### ISSUE THREAD

**Issue by hinds89** [notionparallax/ShadowWolf#662]
- Create list of projects where there is still data in the fields
 - have it cleaned out (data guys)
 - Remove the fields (see picture below)
![image](https://cloud.githubusercontent.com/assets/12288522/8152390/a59f64c0-135f-11e5-8b59-cc41fe07e81d.png)

**Comment by notionparallax** [comment]
run a report on the data and then pass it over to ben

**Comment by Dawil** [comment]
Project Number | Awards | Pictures | Testimonial
---------------+--------+----------+------------
B000704 | "ATIONAL STEEL BUILDING AWARD, AISC  GRAND PRIX AWARD, ENVIRONMENT AWARD AND THE PUBLIC BUILDING AWARD" |  | 
B1103012 | 2014 RAIA Brisbane Regional Commendation - Interior Architecture |  | 
B050603 | 2010 World Architecture - Housing Shortlist 2010 RAIA QLD Residential Architecture - Multiple Housing Commendation |  | 
C0803002 | ACT Institute of Architects Award (Interior Architecture Category) 2012 |  | 
B1408001 |  |  | "thank you for the efforts on Growler and especially the support you have lent to Delamere. The production of the CDR reports is beyond my expectations, and I feel defence particularly undervalue the efforts of industry in these things.  I have enjoyed working with BVN, the level of professionalism across our industry is under more and more pressure all the time, and it is easy to pick off the architects. This has not been the case with BVN and you are leading a good team and the results are testament to this.  I look forward to an opportunity to work together again sometime in the future. James Foreman, Construction Manager, Lend Lease"
B0808008 | 2011 BPN Sustainability Award - Office Fit-out  2011 RAIA QLD Interior Architecture Award 2011 RAIA Brisbane Regional Commendation - Interior Architecture 2011 IDEA Award - Major Commercial |  | 
C0903003 | "AIA ACT Commendation for Public Buildings, 2010" |  | 
C060105 | W. Hayward Morris Award for Interior Architecture; 2010 ACT Institute of Architects Awards |  | 
S971210 | "2003 Silver Medal IOC/IAKS Award, 2000 RAIA Sulman Award, 2000 RAIA Sir Zelman Cowan Award Commendation, 2000 BHP State Colorbond Award, 2000 BHP National Colorbond Award" |  |

**Comment by hinds89** [comment]
@Dawil Should all be good now, maybe have a quick check again of projects to see if any have data in these fields (just in case).

**Comment by Dawil** [comment]
I checked those projects, they're all clean. I'll move on with removing the dirty fields from legacy.
