### ISSUE TITLE
upcase project number letters

### ISSUE THREAD

**Issue by notionparallax** [notionparallax/ShadowWolf#693]

**Comment by hinds89** [comment]
DONE (*ignore):
s971006 => S971006
* ashford000
c0801007 => C0801007
s1201502 => S1201502
s1409514 => S1409514
s1501010 => S1501010
s1102007 => S1102007
s1207513 => S1207513
s990908 => S990908
s0906007 => S0906007
s051252 => S051252
s031019 => S031019
s980566 => S980566
s1211002 => S1211002
s1308004 => S1308004
s0810004 => S0810004
s1311525 => S1311525
s1305005 => S1305005
s0801002 => S0801002
s010630 => S010630
s040611 => S040611
s060102 => S060102
s1412001 => S1412001
s1403004 => S1403004
c1001007 => C1001007
s020422 => S020422
s1210003 => S1210003
s0611016 => S0611016
s060309 => S060309
s1401508 => S1401508
s031004 => S031004
s1305504 => S1305504
s1103009 => S1103009
s1105004 => S1105004
s990313 => S990313
s1501001 => S1501001
s1411002 => S1411002
s0807008 => S0807008
s1407002 => S1407002
s1009005 => S1009005
s060213 => S060213
s1402004 => S1402004
s1409521 => S1409521
s1310001 => S1310001
s1502006 => S1502006
