### ISSUE TITLE
find out what's going on with my dietary requirements

### ISSUE THREAD

**Issue by notionparallax** [notionparallax/ShadowWolf#731]
and if it's happened to other people

**Comment by hinds89** [comment]
6 people have this same problem (Stella ,Ben ,Felix ,Douglas ,Damian ,Scott).  The thing in common with all of these people is that the class of thier `dietary.requirements` is a **String**, everyone else has class **Array** for this.

**Comment by notionparallax** [comment]
I guess we can fix it pretty easily then. Let's discuss tomorrow

**Comment by hinds89** [comment]
DONE
