### ISSUE TITLE
run a report on projects that things in Key Dimensions that aren't measured in m

### ISSUE THREAD

**Issue by notionparallax** [notionparallax/ShadowWolf#743]

**Comment by notionparallax** [comment]
eg, find things that are measured in hotel rooms. then pass that onto the guys to migrate into number of things.

**Comment by hinds89** [comment]
What about things like site area - which is measured in 'hectares' or 'Ha' or 'ha' - just leave them in there and maybe make them all consistant (e.g. make them all 'ha')

**Comment by hinds89** [comment]
(Ran a script to find all projects
 - with units that didn't have 'm' 
 - with measurements filled in but had blank 
 - ignoring those that had a blank measurement)

S011123 units = ha
B970632 units = ha
S1406504 units = ft²
B830403 units = Hectares
B0707006 units = units
S990139 units = Hectares
M1307004 units = Ha
M1307004 units = Ha
B920405 units = Hectares
B940815 units = Hectares
s1305005 units = Ha
S060108 units = ha
B980214 units = ha
S030527 units = ha
S1410009 units = ft²
S1409007 units = Hectares
S1409007 units = Hectares
B1310007 - has blank Unit
B1310007 - has blank Unit
B1310007 - has blank Unit
B1410517 units = ha
B840608 units = ha
M1301522 units = ha
M1003006 - has blank Unit
B040717 units = Hectare
S050711 units = ha
S030804 units = ha
S0705501 units = M
B1404009 units = ha

**Comment by notionparallax** [comment]
I'd say change all to Hectares
the M should probably be a m
We should convert the ft² to m²
