### ISSUE TITLE
Kropach Catlow Farmhouse S000705 - Press Attention no longer has information

### ISSUE THREAD

**Issue by hinds89** [notionparallax/ShadowWolf#749]
I think this issue affects this project only.  There was information in Press Attention which I tried to edit and received an error and eventually the 'blue boxes' have just disappeared (see picture below):
![image](https://cloud.githubusercontent.com/assets/12288522/8469427/fa84127c-20bd-11e5-8196-e1a530cf1705.png)

**Comment by hinds89** [comment]
Thanks @Dawil

**Comment by Dawil** [comment]
This was an interesting condition. It seems like some kind of race condition or unexpected user behavior was able to delete all of the attentions/editable plurals.
