### ISSUE TITLE
2 Projects, 1 Project Number

### ISSUE THREAD

**Issue by Yudianzah** [notionparallax/ShadowWolf#768]
I was able to locate two projects with the same number through Job Numbers and wanted to know if that issue could be fixed? The project number is 'S1505002'.

**Comment by Yudianzah** [comment]
@notionparallax @Dawil

**Comment by hinds89** [comment]
@Yudianzah - That is so weird, I think that is a question for accounts?

**Comment by Yudianzah** [comment]
I was told to raise this as an issue so now i'm very confused as much as you are.

**Comment by hinds89** [comment]
@Yudianzah - as discussed email Kathy and hopefully she can fix it, post the 'answer' here and I can close the issue.  THANKS :)
