### ISSUE TITLE
Patrik Typpo appears at bottom of People List

### ISSUE THREAD

**Issue by Dawil** [notionparallax/ShadowWolf#786]
If Patrik is active then he should appear before the left people not after them.  I think there is something wrong with 'Conditions' for this employee because he has about 10 conditions, most of which are empty (and none with dates).

**Comment by hinds89** [comment]
Only 5 logins have some of their conditions with nil for name field.  However of the 5 all of them, except Patrik, have a date set for at least one of their conditions.

**Comment by hinds89** [comment]
I just added a date to one of the conditions and this seemed to fix the problem.  Can I delete all the conditions except for the most recent?

**Comment by notionparallax** [comment]
don't worry about it. If they work then leave it.
Condition management should be left up to the individual until we develop
some guidelines.
