### ISSUE TITLE
Project Sheet Images

### ISSUE THREAD

**Issue by Yudianzah** [notionparallax/ShadowWolf#790]
Main image in the project sheet needs to be set as a Medium as it currently looks too zoomed in and looks quite blurry.

**Comment by Yudianzah** [comment]
@notionparallax @hinds89

**Comment by notionparallax** [comment]
@hinds89 give me a shout tomorrow and We can make this change together.

**Comment by hinds89** [comment]
DONE c563274b212bc708dc45e7bb1778689a001d2a51
