### ISSUE TITLE
Suspected duplicates on S990608

### ISSUE THREAD

**Issue by DanielMok** [notionparallax/ShadowWolf#793]
Brook/Hull House (S990608) is newly created in P&P but not sure why there is cover image on the project browser for this project when no project file is created in OpenAsset.
I think I have created another project with different project name but same project number S990608.
I suspect that Brook Field House (S990608) existed in P&P which I didn't realise and have created Brook/Hull House (S990608).
However, there is no images stored in Brook Field House (S990608) in OpenAsset either.

@hinds89

**Comment by hinds89** [comment]
Project does exist in OpenAsset and no duplicates exist in P&P (no changes made) - close issue
