### ISSUE TITLE
Project shows different name in project library

### ISSUE THREAD

**Issue by DanielMok** [notionparallax/ShadowWolf#812]
Overseas Passenger Terminal (S990508) appears as 'Sydney Cove Passenger Terminal' in project library home page

**Comment by hinds89** [comment]
This is because there are 2 projects with the same number, I have changed the number of one of them to **S990508-2**.  Now there is:
- S990508 Overseas Passenger Terminal; and
- S990508-2 Sydney Cove Passenger Terminal

**Comment by hinds89** [comment]
Deleted S990508-2, Sydney Cove Passenger Terminal.  It contains very little info (only useful things are the Notes on the Summary tab and the Project Categories which have been copied to S990508).
