### ISSUE TITLE
Photo ranking issue for projects with multiple project sheets

### ISSUE THREAD

**Issue by DanielMok** [notionparallax/ShadowWolf#813]
The photo rankings mess up with the 'main' project sheet although they are specified for the specific project sheet through the description with the quotation "[[ (project sheet tag) ]]".
For example if two images are ranked 10, one for the 'main' and the other for a second project sheet, when the photo for the second project sheet is ranked 10 and being specified for that particular project sheet, it will also appear as one of the images in 'main'.

**Comment by hinds89** [comment]
I think to fix this you can override ratings.  E.g. if you want a picture to appear on top of a project sheet (let's call it workplace) but not on main you would give it a description [[main-5, workplace-10]], I think.  @DanielMok are you able to give me a specific example of which project(s) where this is an issue

**Comment by hinds89** [comment]
Use [[Survivalatsea, main-5]] to override rankings
