### ISSUE TITLE
Project Number Issue

### ISSUE THREAD

**Issue by Yudianzah** [notionparallax/ShadowWolf#846]
Project Number: 'B971152' has been submitted as 'S971152' which is incorrect. Needs to be changed from S to B.

**Comment by Yudianzah** [comment]
@notionparallax @hinds89

**Comment by hinds89** [comment]
You got this @DanielMok?

**Comment by DanielMok** [comment]
ok

**Comment by DanielMok** [comment]
Project number updated to B971152 in P&P. Updated entry in the Process spreadsheet. Deleted project S971152 in Open Asset as there is no images in the folder.

**Comment by hinds89** [comment]
Thanks @DanielMok
