### ISSUE TITLE
Anderson's Office Building

### ISSUE THREAD

**Issue by Yudianzah** [notionparallax/ShadowWolf#847]
So the job number currently set on this project is 'Shane Thompson Andersons Real Estate Office Building'. If possible, could I get this changed to '950758'?

**Comment by Yudianzah** [comment]
@hinds89

**Comment by hinds89** [comment]
This one's for you @tuksun

**Comment by hinds89** [comment]
I have changed the project number on Open Asset Also

**Comment by hinds89** [comment]
Good Job @tuksun
